name: Update JSON Files

on:
  schedule:
    - cron: '*/30 * * * *'  # Runs every 30 minutes
  workflow_dispatch:  # Allows manual trigger

permissions:
  contents: write

jobs:
  update_json:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.8'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests pandas

      - name: Run API script
        env:
          RAPIDAPI_KEY: ${{ secrets.RAPIDAPI_KEY2 }}
        run: |
          python -u arbitrage_research_api.py
          if [ $? -ne 0 ]; then
            echo "API script failed"
            exit 1
          fi

      - name: List generated files
        run: |
          echo "Current directory contents:"
          ls -la *.json || echo "No JSON files found"

      - name: Commit and push changes
        run: |
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git config --global user.name "github-actions[bot]"
          
          echo "Staging changes..."
          git add filtered_data.json
          
          if git diff --staged --quiet; then
            echo "No changes to commit"
          else
            echo "Committing and pushing changes..."
            git commit -m "Update arbitrage data [skip ci]"
            git push
          fi
